controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_shoulder_pan_joint
      - arm_bicep_joint
      - arm_forearm_joint
      - arm_wrist_flex_joint
      - gripper_link_joint
  - name: gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    command_joint: gripper_joint
    joints:
      - gripper_joint
