controller_list:
  - name: fake_pincher_arm_controller
    joints:
      - arm_shoulder_pan_joint
      - arm_bicep_joint
      - arm_forearm_joint
      - arm_wrist_flex_joint
      - gripper_link_joint
  - name: fake_pincher_gripper_controller
    joints:
      - gripper_joint