source: phantomx_pincher_arm.yaml
port: /dev/arbotix
read_rate: 15
write_rate: 25
joints: {
    arm_shoulder_pan_joint: {id: 1,  neutral: 512, max_angle: 100, min_angle: -100, max_speed: 90, type: dynamixel},
    arm_bicep_joint: {id: 2, max_angle: 114, min_angle: -108, max_speed: 90, type: dynamixel},
    arm_forearm_joint: {id: 3, max_angle: 34, min_angle: -91, max_speed: 90, type: dynamixel},
    arm_wrist_flex_joint: {id: 4, max_angle: 96, min_angle: -103, max_speed: 90, type: dynamixel},
    gripper_joint: {id: 5, max_angle: 0, min_angle: -145, max_speed: 90, type: prismatic, radius: .0078, connector: .024, offset: .016}
}
controllers: {
    arm_controller: {type: follow_controller, joints: [arm_shoulder_pan_joint, arm_bicep_joint, arm_forearm_joint, arm_wrist_flex_joint], action_name: arm_controller/follow_joint_trajectory, onboard: False }
}
