turtlebot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  arm_shoulder_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_shoulder_pan_joint
    pid: {p: 32.0, i: 0.01, d: 0.0}
  arm_shoulder_lift_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_shoulder_lift_joint
    pid: {p: 32.0, i: 0.01, d: 0.0}
  arm_elbow_flex_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_elbow_flex_joint
    pid: {p: 32.0, i: 0.01, d: 0.0}
  arm_wrist_flex_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_wrist_flex_joint
    pid: {p: 32.0, i: 0.01, d: 0.0}